### ISSUE TITLE
Cross-compilation fails on Ubuntu 18.10

### ISSUE THREAD

**Issue by Luni-4** [TypesettingTools/libass#1]
On `Ubuntu 18.10`, I get the following error when I try to cross-compile with `i686-w64-mingw32-gcc (gcc 7.3.0)`

```
../libass/ass.c: In function ‘process_info_line’:
../libass/ass.c:612:27: error: implicit declaration of function ‘strndup’ [-Werror=implicit-function-declaration]
         track->Language = strndup(p, 2);
                           ^~~~~~~
../libass/ass.c:612:27: warning: incompatible implicit declaration of built-in function ‘strndup’
```

**Comment by CoffeeFlux** [comment]
Can you paste the full cross compilation settings used?

**Comment by Luni-4** [comment]
> Can you paste the full cross compilation settings used?

```
[binaries]
c = 'i686-w64-mingw32-gcc'
cpp = 'i686-w64-mingw32-g++'
ar = 'i686-w64-mingw32-ar'
strip = 'i686-w64-mingw32-strip'
pkgconfig = 'i686-w64-mingw32-pkg-config'
windres = 'i686-w64-mingw32-windres'
exe_wrapper = 'wine' # A command used to run generated executables.

[host_machine]
system = 'windows'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'
```

**Comment by CoffeeFlux** [comment]
See if this solves the issue: https://github.com/TypesettingTools/libass/commit/c722a0103804484e0a59f03d58dccea4f44c59ee

**Comment by Luni-4** [comment]
It works perfectly now! Thanks for fixing it!
